/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package presentacion;

import domain.CuentaBancaria;
import javax.swing.JOptionPane;

/**
 *
 * @author 50765
 */
public class JFrmDialog extends javax.swing.JDialog {

    private CuentaBancaria cuenta = new CuentaBancaria();
    
    public JFrmDialog(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        setLocationRelativeTo(null);
    }
    
       
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panel_principal = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        textarea_resultado = new javax.swing.JTextArea();
        jLabel1 = new javax.swing.JLabel();
        btn_insert = new javax.swing.JButton();
        btn_retirar = new javax.swing.JButton();
        btn_consultar = new javax.swing.JButton();
        txtfld_monto = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtfld_numCuenta = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtfld_titular = new javax.swing.JTextField();
        label_numCuenta = new javax.swing.JLabel();
        label_titular = new javax.swing.JLabel();
        btn_confirm = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jScrollPane1.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPane1.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_NEVER);

        textarea_resultado.setEditable(false);
        textarea_resultado.setColumns(20);
        textarea_resultado.setFont(new java.awt.Font("Calisto MT", 1, 14)); // NOI18N
        textarea_resultado.setRows(5);
        jScrollPane1.setViewportView(textarea_resultado);

        jLabel1.setText("Problema :6");

        btn_insert.setFont(new java.awt.Font("Calisto MT", 0, 12)); // NOI18N
        btn_insert.setText("INSERTAR");
        btn_insert.setEnabled(false);
        btn_insert.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_insertActionPerformed(evt);
            }
        });

        btn_retirar.setFont(new java.awt.Font("Calisto MT", 0, 12)); // NOI18N
        btn_retirar.setText("RETIRAR");
        btn_retirar.setEnabled(false);
        btn_retirar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_retirarActionPerformed(evt);
            }
        });

        btn_consultar.setFont(new java.awt.Font("Calisto MT", 0, 12)); // NOI18N
        btn_consultar.setText("CONSULTAR");
        btn_consultar.setEnabled(false);
        btn_consultar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_consultarActionPerformed(evt);
            }
        });

        txtfld_monto.setFont(new java.awt.Font("Calisto MT", 0, 12)); // NOI18N
        txtfld_monto.setForeground(new java.awt.Color(51, 51, 51));
        txtfld_monto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtfld_montoActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Calisto MT", 1, 12)); // NOI18N
        jLabel2.setText("Monto:");

        jLabel3.setFont(new java.awt.Font("Calisto MT", 1, 12)); // NOI18N
        jLabel3.setText("Nº Cuenta:");

        txtfld_numCuenta.setFont(new java.awt.Font("Calisto MT", 0, 12)); // NOI18N
        txtfld_numCuenta.setForeground(new java.awt.Color(51, 51, 51));
        txtfld_numCuenta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtfld_numCuentaActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Calisto MT", 1, 12)); // NOI18N
        jLabel4.setText("Titular:");

        txtfld_titular.setFont(new java.awt.Font("Calisto MT", 0, 12)); // NOI18N
        txtfld_titular.setForeground(new java.awt.Color(51, 51, 51));
        txtfld_titular.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtfld_titularActionPerformed(evt);
            }
        });

        label_numCuenta.setFont(new java.awt.Font("Calisto MT", 1, 12)); // NOI18N
        label_numCuenta.setText("Nº:");

        label_titular.setFont(new java.awt.Font("Calisto MT", 1, 12)); // NOI18N
        label_titular.setText("Titular: ");

        btn_confirm.setFont(new java.awt.Font("Calisto MT", 0, 12)); // NOI18N
        btn_confirm.setText("CONFIRMAR");
        btn_confirm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_confirmActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panel_principalLayout = new javax.swing.GroupLayout(panel_principal);
        panel_principal.setLayout(panel_principalLayout);
        panel_principalLayout.setHorizontalGroup(
            panel_principalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_principalLayout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(panel_principalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panel_principalLayout.createSequentialGroup()
                        .addComponent(btn_confirm)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(panel_principalLayout.createSequentialGroup()
                        .addGroup(panel_principalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panel_principalLayout.createSequentialGroup()
                                .addGroup(panel_principalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, panel_principalLayout.createSequentialGroup()
                                        .addComponent(jLabel1)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(label_numCuenta))
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, panel_principalLayout.createSequentialGroup()
                                        .addComponent(jLabel3)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(txtfld_numCuenta, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, panel_principalLayout.createSequentialGroup()
                                        .addComponent(jLabel4)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(txtfld_titular, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGroup(panel_principalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(panel_principalLayout.createSequentialGroup()
                                        .addGap(36, 36, 36)
                                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(panel_principalLayout.createSequentialGroup()
                                        .addGap(91, 91, 91)
                                        .addGroup(panel_principalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(btn_consultar)
                                            .addGroup(panel_principalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                .addComponent(btn_retirar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(btn_insert, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                                    .addGroup(panel_principalLayout.createSequentialGroup()
                                        .addGap(46, 46, 46)
                                        .addComponent(label_titular))))
                            .addGroup(panel_principalLayout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtfld_monto, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap(21, Short.MAX_VALUE))))
        );
        panel_principalLayout.setVerticalGroup(
            panel_principalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_principalLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(42, 42, 42)
                .addGroup(panel_principalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtfld_numCuenta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 32, Short.MAX_VALUE)
                .addGroup(panel_principalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtfld_titular, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(panel_principalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtfld_monto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 27, Short.MAX_VALUE)
                .addComponent(btn_confirm)
                .addGap(26, 26, 26))
            .addGroup(panel_principalLayout.createSequentialGroup()
                .addGroup(panel_principalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(label_titular)
                    .addComponent(label_numCuenta))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btn_insert)
                .addGap(18, 18, 18)
                .addComponent(btn_retirar)
                .addGap(18, 18, 18)
                .addComponent(btn_consultar)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panel_principal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panel_principal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_consultarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_consultarActionPerformed
        textarea_resultado.setText(cuenta.consultarSaldo()); 
        
    }//GEN-LAST:event_btn_consultarActionPerformed

    private void btn_retirarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_retirarActionPerformed
        if(Double.parseDouble(txtfld_monto.getText())>cuenta.getSaldo()){
            JOptionPane.showMessageDialog(null, "Error, No cuenta con saldo Suficiente","Error Monto",JOptionPane.ERROR_MESSAGE);
        }
        else{
            cuenta.retirarDinero(Double.parseDouble(txtfld_monto.getText())); 
            JOptionPane.showMessageDialog(null, "Se ha retirado dinero Correctamente!");
            JOptionPane.showMessageDialog(null, "Se ha retirado Dinero Correctamente!"+"\nHa Retirado: "+txtfld_monto.getText()+"$ A la cuenta" 
                    +"\nCuenta Nº:"+cuenta.getNumeroCuenta() +"\nTitular : "+cuenta.getNombreTitular()); 
        }
        
    }//GEN-LAST:event_btn_retirarActionPerformed

    private void txtfld_montoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtfld_montoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtfld_montoActionPerformed

    private void txtfld_numCuentaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtfld_numCuentaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtfld_numCuentaActionPerformed

    private void btn_insertActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_insertActionPerformed
        // TODO add your handling code here: 
        
        this.cuenta.ingresarDinero(Double.parseDouble(txtfld_monto.getText())); 
        JOptionPane.showMessageDialog(null, "Se ha Ingresado Dinero Correctamente!"+"\nHa Agregado: "+txtfld_monto.getText()+"$ A la cuenta" 
                +"\nCuenta Nº:"+cuenta.getNumeroCuenta()+"\nTitular : "+cuenta.getNombreTitular()); 
        
    }//GEN-LAST:event_btn_insertActionPerformed

    private void btn_confirmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_confirmActionPerformed
        // TODO add your handling code here: 
       
        btn_insert.setEnabled(true); 
        btn_consultar.setEnabled(true);
        btn_retirar.setEnabled(true);  
        cuenta.setNombreTitular(txtfld_titular.getText());
        cuenta.setNumeroCuenta(Integer.parseInt(txtfld_numCuenta.getText())); 
        cuenta.setSaldo(Double.parseDouble(txtfld_monto.getText())); 
        
        label_numCuenta.setText("Nº:"+String.valueOf(cuenta.getNumeroCuenta())); 
        label_titular.setText("Titular:"+cuenta.getNombreTitular());  
        
        txtfld_titular.setEnabled(false); 
        txtfld_numCuenta.setEnabled(false); 
        btn_confirm.setEnabled(false); 
        
        JOptionPane.showMessageDialog(null, "Se ha registrado Correctamente!");
    }//GEN-LAST:event_btn_confirmActionPerformed

    private void txtfld_titularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtfld_titularActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtfld_titularActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JFrmDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JFrmDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JFrmDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFrmDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                JFrmDialog dialog = new JFrmDialog(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_confirm;
    private javax.swing.JButton btn_consultar;
    private javax.swing.JButton btn_insert;
    private javax.swing.JButton btn_retirar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel label_numCuenta;
    private javax.swing.JLabel label_titular;
    private javax.swing.JPanel panel_principal;
    private javax.swing.JTextArea textarea_resultado;
    private javax.swing.JTextField txtfld_monto;
    private javax.swing.JTextField txtfld_numCuenta;
    private javax.swing.JTextField txtfld_titular;
    // End of variables declaration//GEN-END:variables
}
